# -*- coding: utf-8 -*-
"""E_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/159VRmI_fPbCilu93nTX9Mgk81JQUGPau

**Ejercicio N°. 1**
"""

print("Hola, soy Fraven\nEstoy empezando el curso de python\nEspero aprender mucho")